### ISSUE TITLE
request: print elapsed time during call to stop

### ISSUE THREAD

**Issue by btracey** [davecheney/profile#3]
It would be nice if during the call to Stop(), profile logged the total elapsed time. This would give a quick answer to "how fast did my code run" before one takes a more in-depth look at the pprof output.

**Comment by davecheney** [comment]
THIS PROJECT HAS MOVED TO github.com/pkg/profile

Please do not use this package. Please do not report issues against this package. Please migrate to github.com/pkg/profile
