### ISSUE TITLE
Empty cpu.pprof

### ISSUE THREAD

**Issue by mDomingues** [davecheney/profile#7]
Following your instructions and with the default configs, when I run go tool pprof got "runtime error: index out of range". cpu.pprof is always empty, no matter how long I use the app.

Any ideas ? 
Many thanks

**Comment by davecheney** [comment]
Can you share your code?

**Comment by mDomingues** [comment]
All my app code ? It's a lot.

**Comment by davecheney** [comment]
Just the bits where you use the profile package.

**Comment by mDomingues** [comment]
It's a web app with a lot of code. I just did the import and add that code to run the profiler:
 defer profile.Start(profile.CPUProfile).Stop()

Basically I followed this: https://medium.com/code-adventures/profiling-golang-851db2d9ae24

**Comment by davecheney** [comment]
Then if you app exits cleanly you should get a working profile.

Are you using a Mac?

**Comment by mDomingues** [comment]
Yes I am

**Comment by davecheney** [comment]
I'm sorry to report that profiling is not reliable on macs,
https://groups.google.com/d/msg/golang-nuts/0Sre9xE9l-Q/64lbXswU3dMJ

**Comment by mDomingues** [comment]
It probably explains the problems. Some other users with OSX face them too.
Thank you @davecheney

**Comment by SmaugTheGreat** [comment]
Is this also not working under Windows?

**Comment by davecheney** [comment]
@SmaugTheGreat please see GitHub.com/pkg/profile
