### ISSUE TITLE
No output in the profile file

### ISSUE THREAD

**Issue by astrekalova** [davecheney/profile#8]
I want to profile a simple webserver that I wrote in Go. It accepts requests, maps the request to avro object and sends it to Kafka in a go routine. The requirement is that it answers immediately and sends an object to Kafka later. Locally it answers in under 1 ms on average. I have been trying to profile it by starting the script with profile package and sending test requests with jmeter at the same time. I can see in the output that the profile file is generated but it remains empty, no matter how long jmeter is sending the requests. I'm running it on Mac El Capitan. I read that there were some issues with profiling on Mac but it would be working on El Capitan. Do you have any tips?

**Comment by davecheney** [comment]
The profile file is buffered in memory. The profile package flushes the
profile to disk when the program exits. If you need to profile a running
application I recommend the http/pprof package.

Thanks

Dave

**Comment by davecheney** [comment]
THIS PROJECT HAS MOVED TO github.com/pkg/profile

Please do not use this package. Please do not report issues against this package. Please migrate to github.com/pkg/profile
