### ISSUE TITLE
No output about MemProfile

### ISSUE THREAD

**Issue by ruinanchen** [davecheney/profile#9]
I set memprofile true to enable mem statitistic, but mem.pprof 's output is empty. I think there is a bug and I try fix it. I add "pprof.WriteHeapProfile(f)" in 131 line of profile.go.

**Comment by davecheney** [comment]
@ruinanchen thanks for your bug report, could you 

a. show me the code where you enabled the memory profile
b. send a PR with your proposed fix.

**Comment by davecheney** [comment]
oh, sorry, you are using the old version of this package, please use github.com/pkg/profile

**Comment by ruinanchen** [comment]
Thanks very much. I will use github.com/pkg/profile.

**Comment by davecheney** [comment]
THIS PROJECT HAS MOVED TO github.com/pkg/profile

Please do not use this package. Please do not report issues against this package. Please migrate to github.com/pkg/profile
